load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

# 第一层依赖
git_repository(
    name = "lib_first",
    init_submodules = True,
    remote = "http://videobase:video147258369BASE@git.code.oa.com/allencheng/bazel_first_depends.git",
    tag = "v4.0",
)
# 第二层依赖
git_repository(
    name = "lib_second",
    init_submodules = True,
    remote = "http://videobase:video147258369BASE@git.code.oa.com/allencheng/bazel_second_depends.git",
    tag = "v2.0",
)
# 依赖预编译好的项目
new_git_repository(
    name = "lib_static",
    init_submodules = True,
    remote = "http://videobase:video147258369BASE@git.code.oa.com/allencheng/bazel_static_depends.git",
    branch = "master",
    build_file_content = """
cc_library(
    name = "hello-echo",
    srcs = glob(["*.a"]),
    hdrs = ["hello-echo.h"],
    visibility = ["//visibility:public"],
)
    """
)


# GoogleTest/GoogleMock framework. Used by most unit-tests.
http_archive(
    name = "com_google_googletest",
    urls = ["https://github.com/google/googletest/archive/b6cd405286ed8635ece71c72f118e659f4ade3fb.zip"],
    strip_prefix = "googletest-b6cd405286ed8635ece71c72f118e659f4ade3fb",
    sha256 = "ff7a82736e158c077e76188232eac77913a15dac0b22508c390ab3f88e6d6d86",
)
# build_file = "gtest.BUILD",

#git_repository(
#    name = "googletest",
#    remote = "https://github.com/google/googletest",
#    tag = "release-1.8.0",
#)