@startuml class-streamlib

!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.puml
!include https://unpkg.com/plantuml-style-c4@latest/class-diagram-helper.puml
' uncomment the following line and comment the first to use locally
'!include class-diagram-helper.puml

GREY_ARROW

interface av.CodecData {
    Type() CodecType
}

interface av.VideoCodecData {
    Width() int
	Height() int
}

interface av.AudioCodecData {
    SampleFormat() SampleFormat
	SampleRate() int
	ChannelLayout() ChannelLayout
	PacketDuration([]byte) (time.Duration, error)
}

interface av.PacketWriter {
	WritePacket(Packet) error
}

interface av.PacketReader {
	ReadPacket() (Packet, error)
}

interface av.Muxer {
	WriteHeader([]CodecData) error
	WriteTrailer() error
}

interface av.Demuxer {
	Streams() ([]CodecData, error)
}

interface av.MuxCloser {
	Close() error
}

interface av.DemuxCloser {
	Close() error
}

class flv.Demuxer {
    prober *Prober
	bufr   *bufio.Reader
}

class flv.Muxer {
    bufw    writeFlusher
	b       []byte
	streams []av.CodecData
}

class flv.Prober {
    Streams  []av.CodecData
	CachedPkts []av.Packet
}

class codec.h264.CodecData {
    AVCDecoderConfRecordBytes() []byte
    SPS() []byte
    PPS() []byte
}
class codec.aac.CodecData {}

class HandlerMuxer {
}

class HandlerDemuxer {
}

av.CodecData<|--av.VideoCodecData
av.CodecData<|--av.AudioCodecData
av.PacketReader<|-- av.Demuxer
av.PacketWriter<|--av.Muxer
av.Demuxer<|-- av.DemuxCloser
av.Muxer<|--av.MuxCloser
av.Demuxer<|..flv.Demuxer
av.Demuxer-[hidden]-->flv.Demuxer
av.Muxer<|..flv.Muxer
av.Muxer-[hidden]-->flv.Muxer
av.DemuxCloser<|..HandlerDemuxer
av.MuxCloser<|..HandlerMuxer
flv.Demuxer<--HandlerDemuxer
flv.Muxer<--HandlerMuxer
flv.Demuxer<-flv.Prober
av.VideoCodecData<|--codec.h264.CodecData
av.VideoCodecData -[hidden]--> codec.h264.CodecData
av.AudioCodecData<|--codec.aac.CodecData
av.AudioCodecData-[hidden]--> codec.aac.CodecData
' av.CodecData<--flv.Muxer
@enduml