@startuml class-streammanager

!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.puml
!include https://unpkg.com/plantuml-style-c4@latest/class-diagram-helper.puml
' uncomment the following line and comment the first to use locally
'!include class-diagram-helper.puml

GREY_ARROW

class stream.Stream {
    players []stream.rtmp.Player  
    players []stream.httpflv.Player  
    forwarders []stream.Player  
    publisher stream.rtmp.Publisher
}

package stream {
    package rtmp {}
    package httpflv {}
}

' stream.Stream "1" *-- "n" stream.StreamHandler

stream.Stream "1" *-- "1" stream.rtmp.Publisher
stream.Stream "1" *-- "1..n" stream.rtmp.Player

stream.Stream "1" *-- "1" stream.httpflv.Publisher
stream.Stream "1" *-- "1..n" stream.httpflv.Player

stream.streams "1" *-- "n" stream.Stream

@enduml