@startuml class-queue

!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.puml
!include https://unpkg.com/plantuml-style-c4@latest/class-diagram-helper.puml
' uncomment the following line and comment the first to use locally
'!include class-diagram-helper.puml

GREY_ARROW

interface av.Muxer {
	WriteHeader([]CodecData) error
	WriteTrailer() error
}

interface av.Demuxer {
	Streams() ([]CodecData, error)
}

av.Muxer <|.. avque.Queue
av.Demuxer <|.. avque.QueueCursor

avque.QueueCursor ->avque.Queue

@enduml