@startuml class-rtmpserver

!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.puml
!include https://unpkg.com/plantuml-style-c4@latest/class-diagram-helper.puml
' uncomment the following line and comment the first to use locally
'!include class-diagram-helper.puml

GREY_ARROW

package stream {
    package rtmp {}
}

class server.RTMPServer {
}
server.RTMPServer-->stream.rtmp.PreHandler
server.RTMPServer-->stream.rtmp.Ingester
server.RTMPServer-->stream.rtmp.Receiver
server.RTMPServer-->stream.rtmp.Forwarder
server.RTMPServer-->stream.rtmp.Player


@enduml