@startuml rtmpserver-sequence
!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.pum

title <size:20>接收rtmp流流程</size>

actor User
participant "SLive" as SLive
participant "RTMPServer" as RTMPServer
participant "Service" as RTMPService
participant "Forwarder" as RTMPForwarder
participant "Producer" as RTMPProducer
participant "Consumer" as RTMPConsumer
participant "Session" as RTMPSession
participant "Queue" as Queue
participant "QueueCursor" as QueueCursor

== RTMPServer启动 ==
SLive->SLive: GetGlobalConfig()(获取server监听参数)
SLive->RTMPServer: ListenAndServe("rtmp", "10.10.10.10:1935")
== 接收推流流程 ==
User->SLive: 推流rtmp://host/mountpoint/streamID
SLive->RTMPServer: Serve(net.Conn)
RTMPServer->RTMPService: NewRTMPService(net.Conn)
RTMPServer->RTMPService: Prepare()
RTMPService->RTMPService: Prepare()
RTMPService->PreHandler: NewPreHandler(conn)
RTMPService->PreHandler: Handle(conn)
PreHandler->RTMPSession: HandshakeServer()
PreHandler->RTMPSession: ReadConnect()
PreHandler->PreHandler: checkHost()
RTMPService->PreHandler: IsPublishing()(如果是publish命令)
RTMPService->RTMPForwarder: NewRTMPForwarder(conn)
RTMPForwarder->RTMPForwarder: NewRTMPProducer(conn)
RTMPForwarder->RTMPForwarder: CreateForwarderSource()
RTMPService->RTMPForwarder: Cycle()
loop
    RTMPForwarder->RTMPForwarder: ContextDone(ctx)
    alt timeout或canceled
        RTMPForwarder->RTMPForwarder: Stop()
        RTMPForwarder->RTMPProducer: Close()
        destroy RTMPProducer
    else 
        RTMPForwarder->RTMPForwarder: processMsg()
        RTMPForwarder->RTMPProducer: Produce()
        RTMPProducer->RTMPSession: ReadHeaders()
        RTMPProducer->Queue: WriteReaders()
        RTMPProducer->RTMPSession: ReadPacket()
        RTMPProducer->Queue: WritePacket()
        RTMPProducer->RTMPSession: ReadCommand()
        alt deleteStream或FCUnpublish
            RTMPProducer->RTMPProducer: PrintLog()
        end
    end
end
RTMPForwarder->RTMPForwarder: GetForwardSources()
loop [每个ForwardSource一个gorotine]
    RTMPForwarder->RTMPForwarder: ContextDone(ctx)
    alt timeout或canceled
        RTMPForwarder->RTMPForwarder: Stop()
        RTMPForwarder->RTMPConsumer: Close()
        destroy RTMPConsumer
    else 
        RTMPForwarder->ForwardSource: GetUrl()
        RTMPForwarder->RTMPForwarder: NewRTMPConsumer(url)
        RTMPForwarder->RTMPConsumer: Consume()
        RTMPConsumer->RTMPSession: HandshakeClient()
        RTMPConsumer->RTMPSession: ReadConnect()
        RTMPConsumer->QueueCursor: GetHeaders()
        RTMPConsumer->RTMPSession: WriteHeaders()
        RTMPConsumer->QueueCursor: GetPacket()
        RTMPConsumer->RTMPSession: WritePacket()
    end
end
@enduml