@startuml rtmpserver-sequence
!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.pum

title <size:20>接收rtmp流流程</size>

actor User
participant "SLive" as SLive
participant "RTMPServer" as RTMPServer
participant "RTMPReceiver" as RTMPReceiver
participant "RTMPSession" as RTMPSession
participant "Queue" as GOPCache

== RTMPServer启动 ==
SLive->SLive: GetGlobalConfig()(获取server监听参数)
SLive->RTMPServer: ListenAndServe("rtmp", "10.10.10.10:1935")
== 接收推流流程 ==
User->SLive: 推流rtmp://host/mountpoint/streamID
SLive->RTMPServer: Serve(net.Conn)
RTMPServer->RTMPReceiver: NewRTMPReceiver(net.Conn)
RTMPServer->RTMPReceiver: Prepare()
RTMPReceiver->RTMPSession: HandshakeServer()
RTMPReceiver->RTMPSession: ReadConnect()
RTMPReceiver->RTMPSession: IsPublishing()(如果是publish命令)
RTMPReceiver->RTMPReceiver: checkHost
RTMPReceiver->RTMPServer: 成功建立RTMP连接
RTMPReceiver->RTMPPublisher: NewRTMPPublisher()
RTMPReceiver->RTMPPublisher: Cycle()(新启goroutine执行)
loop
    RTMPPublisher->RTMPPublisher: ContextDone(ctx)
    alt timeout或canceled
        RTMPPublisher->RTMPPublisher: Stop()
        destroy RTMPPublisher
    else 
        RTMPPublisher->RTMPPublisher: processMsg()
        RTMPPublisher->RTMPSession: ReadHeaders()
        RTMPPublisher->GOPCache: PushHeader()
        RTMPPublisher->RTMPSession: ReadPacket()
        RTMPPublisher->GOPCache: PushPacket()
        RTMPPublisher->RTMPPublisher: processCmd()
        RTMPPublisher->RTMPSession: ReadCommand()
        alt deleteStream或FCUnpublish
            RTMPPublisher->RTMPPublisher: Stop()
            destroy RTMPPublisher
        end
    end
end
@enduml