@startuml rtmpplay-sequence
!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.pum

title <size:20>播放rtmp流流程</size>

actor User
participant "SLive" as SLive
participant "RTMPServer" as RTMPServer
participant "Service" as RTMPService
participant "Player" as RTMPlayer
participant "Consumer" as RTMPConsumer
participant "Producer" as RTMPProducer
participant "Session" as RTMPSession
participant "QueueCursor" as QueueCursor
participant "Ingester" as RTMPIngester
participant "Queue" as Queue

User->SLive: 播放rtmp://host/mountpoint/streamID
SLive->RTMPServer: Serve(net.Conn)
RTMPServer->RTMPService: NewRTMPService(net.Conn)
RTMPServer->RTMPService: Prepare()
RTMPService->RTMPService: Prepare()
RTMPService->PreHandler: NewPreHandler(conn)
RTMPService->PreHandler: Handle(conn)
PreHandler->RTMPSession: HandshakeServer()
PreHandler->RTMPSession: ReadConnect()
PreHandler->PreHandler: checkHost()
RTMPService->PreHandler: IsPlaying()(如果是Play命令)
RTMPService->RTMPService: existStream()
RTMPService->RTMPlayer: NewRTMPlayer(conn)
alt [本机不存在该流]
    RTMPlayer->Queue: CreateQueue()
else [本机存在该流]
    RTMPService->RTMPService: GetQueueCursor() 
end
RTMPlayer->RTMPConsumer: NewRTMPConsume(conn, queueCursor)
RTMPService->RTMPlayer: Cycle()
loop
    RTMPlayer->RTMPlayer: ContextDone(ctx)
    alt timeout或canceled
        RTMPlayer->RTMPlayer: Stop()
        RTMPConsumer->RTMPConsumer: Close()
        destroy RTMPConsumer
        destroy RTMPlayer
    else 
        RTMPlayer->RTMPlayer: processMsg()
        RTMPlayer->RTMPConsumer: Consume()
        RTMPConsumer->QueueCursor: ReadHeaders()
        RTMPConsumer->RTMPSession: WriteHeaders()
        RTMPConsumer->QueueCursor: ReadPacket()
        RTMPConsumer->RTMPSession: WritePacket()
        RTMPConsumer->RTMPSession: ReadCommand()
        alt deleteStream
            RTMPlayer->RTMPlayer: Stop()
            RTMPConsumer->RTMPConsumer: Close()
            destroy RTMPConsumer
            destroy RTMPlayer
        end
    end
end
alt [本机不存在该流]
    RTMPService->StreamStat: GetStreamStat()
    alt [远端没有存在该流]
        RTMPService->RTMPService: 返回失败()
        RTMPService->RTMPlayer: stop()
        RTMPConsumer->RTMPConsumer: Close()
        destroy RTMPConsumer
        destroy RTMPlayer
    else
    RTMPService->RTMPService: CreateUrl()
    RTMPService->RTMPIngester: NewRTMPIngester(url)
    RTMPService->RTMPIngester: Prepare()
    RTMPIngester->RTMPProducer: Prepare()
    RTMPIngester->RTMPProducer: NewRTMPProducer(url, queue)
    RTMPProducer->RTMPSession: HandshakeClient()
    RTMPProducer->RTMPSession: ReadConnect()
    RTMPProducer-->RTMPIngester: Prepare()
    RTMPIngester-->RTMPService: Prepare()
    RTMPService->RTMPIngester: Cycle()
    loop
        RTMPIngester->RTMPIngester: ContextDone(ctx)
        alt timeout或canceled
            RTMPIngester->RTMPIngester: Stop()
            RTMPIngester->RTMPProducer: Close()
            destroy RTMPProducer
        else 
            RTMPIngester->RTMPIngester: processMsg()
            RTMPIngester->RTMPProducer: Produce()
            RTMPProducer->RTMPSession: ReadHeaders()
            RTMPProducer->Queue: WriteHeaders()
            RTMPProducer->RTMPSession: ReadPacket()
            RTMPProducer->Queue: WritePacket()
            RTMPProducer->RTMPSession: ReadCommand()
            alt deleteStream或FCUnpublish
                RTMPProducer->RTMPProducer: PrintLog()
            end
        end
    end
end

@enduml