@startuml state-ingester
!include https://unpkg.com/plantuml-style-c4@latest/core.puml
' uncomment the following line and comment the first to use locally
'!include core.puml

GREEN_ARROW

' title Ingester States

[*] -> StatusInit: 切换为拉流模式
StatusInit: Prepare()
StatusInit -> StatusOK : success
StatusOK: CopyAV()
StatusOK --> StatusOK: success
StatusOK --> StatusError: fail
StatusError: WaitTimeout()
StatusError --> StatusError: wait
StatusError --> StatusDeath: timeout
StatusDeath -> [*]: death

@enduml